 CLASS zcl_test_booking_24 DEFINITION
  PUBLIC FINAL
  CREATE PUBLIC
  FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS zcl_test_booking_24 IMPLEMENTATION.
 ENDCLASS.
